// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $FileUploadContext from "./islands/FileUploadContext.tsx";
import * as $Graph_Graph from "./islands/Graph/Graph.tsx";
import * as $Graph_SidePanel from "./islands/Graph/SidePanel.tsx";
import * as $Graph_ToolBar from "./islands/Graph/ToolBar.tsx";
import * as $Results from "./islands/Results.tsx";
import * as $UploadForm from "./islands/UploadForm.tsx";
import * as $ViewSwitcher from "./islands/ViewSwitcher.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/FileUploadContext.tsx": $FileUploadContext,
    "./islands/Graph/Graph.tsx": $Graph_Graph,
    "./islands/Graph/SidePanel.tsx": $Graph_SidePanel,
    "./islands/Graph/ToolBar.tsx": $Graph_ToolBar,
    "./islands/Results.tsx": $Results,
    "./islands/UploadForm.tsx": $UploadForm,
    "./islands/ViewSwitcher.tsx": $ViewSwitcher,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
