[package]
name = "pcap_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
pcap-parser = "0.15.0"
pnet = { version = "0.34.0", default-features = false }
sha1 = "0.10.6"
sha2 = "0.10.8"
